=== flor3kk/TechnologieInternetowe/jakis poczatek/lab7/emails.dtd
<!ELEMENT emails (email+)>
<!ELEMENT email (to, from, heading, body, attachements*)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT attachements ( attachement+ )>
<!ELEMENT attachement ( name )>
<!ELEMENT name (#PCDATA)>

=== flor3kk/TechnologieInternetowe/jakis poczatek/lab7/email.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE emails SYSTEM "emails.dtd">
<emails>
    <email> 
        <to>address@mail.com</to> 
        <from>Spam</from> 
        <heading>Offer</heading> 
        <body>Do you want to buy our products?</body> 
    </email> 
    <email> 
        <to>address@mail.com</to> 
        <from>coworker@mail.com</from> 
        <heading>Document</heading> 
        <body>Please see this document and reply asap.</body>
        <attachements>
                <attachement>
                <name>Document.odt</name>
            </attachement>
        </attachements> 
    </email> 
    
    <email> 
        <to>address@mail.com</to> 
        <from>coworker@mail.com</from> 
        <heading>Document</heading> 
        <body>Please see this document and reply asap.</body>
        <attachements>
            <attachement>
            <name>Document.odt</name>
            </attachement>
        
            <attachement>
                <name>Document.odt</name>
            </attachement>
            <attachement>
                <name>Document.odt</name>
            </attachement>
        </attachements> 
    </email> 
    
</emails>
