=== flor3kk/TechnologieInternetowe/jakis poczatek/lab7/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:attribute name="type" default="residence">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="residence"/>
                <xs:enumeration value="correspondence"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" minOccurs="1" />
                <xs:element name="surname" type="xs:string" minOccurs="1" />
                <xs:element name="address" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="city" type="xs:string" minOccurs="1">
                            </xs:element>
                            <xs:element name="street" type="xs:string" minOccurs="1" />
                        </xs:sequence>
                        <xs:attribute ref="type" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== flor3kk/TechnologieInternetowe/jakis poczatek/lab7/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-stylesheet type="text/css" href="person.css"?> -->
<!-- <?xml-stylesheet type="text/xsl" href="person.xsl"?> -->

<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="person.xsd">
 <name>Jan</name>
 <surname>Kowalski</surname>
<address>
    <city>Rzeszów</city>
    <street>Rejtana 16c</street>
    </address>
    <address type="correspondence">
    <city>Rzeszów</city>
    <street>Rejtana 16c</street>
    </address>
   </person>
