=== flor3kk/TechnologieInternetowe/jakis poczatek/lab7/rozklad.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rozklad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="train_info" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nr_poc" type="xs:int"/>
                            <xs:element name="nazwa" type="xs:string"/>
                            <xs:element name="rodzaj" type="xs:string"/>
                            <xs:element name="nazwa_poc" type="xs:string"/>
                            <xs:element name="stations">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="station_info" minOccurs="2" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="station" type="xs:string"/>
                                                    <xs:element name="godz_przyj" type="xs:dateTime"/>
                                                    <xs:element name="godz_odj" type="xs:dateTime"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="wagony" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="wagony_info" minOccurs="1" maxOccurs="5">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nazwa_wag" type="xs:string" />
                                                    <xs:element name="ilosc" type="xs:int"/>                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== flor3kk/TechnologieInternetowe/jakis poczatek/lab7/rozklad.xml
<?xml version="1.0" encoding="UTF-8"?> 

<rozklad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="rozklad.xsd">

    <train_info>
        <nr_poc>1</nr_poc>
        <nazwa>Florek</nazwa>
        <rodzaj>osoboby</rodzaj>
        <nazwa_poc>pendolino</nazwa_poc>
        <stations>
            <station_info>
                <station>frysztak</station>
                <godz_przyj>2022-05-30T09:00:00</godz_przyj>
                <godz_odj>2022-05-30T09:00:00</godz_odj>
            </station_info>
            <station_info>
                <station> krosno </station>
                <godz_przyj>2022-05-30T09:00:00</godz_przyj>
                <godz_odj>2022-05-30T09:00:00</godz_odj>
            </station_info>
        </stations>
        
        <wagony>
            <wagony_info>
                <nazwa_wag>restauracyjny</nazwa_wag>
                <ilosc>2</ilosc>
            </wagony_info>
        </wagony>
    </train_info>

    <train_info>
        <nr_poc>2</nr_poc>
        <nazwa>Florek</nazwa>
        <rodzaj>osoboby</rodzaj>
        <nazwa_poc>pendolino</nazwa_poc>
        <stations>
            <station_info>
                <station>frysztak</station>
                <godz_przyj>2022-05-30T09:00:00</godz_przyj>
                <godz_odj>2022-05-30T09:00:00</godz_odj>
            </station_info>
            <station_info>
                <station> krosno </station>
                <godz_przyj>2022-05-30T09:00:00</godz_przyj>
                <godz_odj>2022-05-30T09:00:00</godz_odj>
            </station_info>
        </stations>

        <wagony>
            <wagony_info>
                <nazwa_wag>restauracyjny</nazwa_wag>
                <ilosc>2</ilosc>
            </wagony_info>
        </wagony>
    </train_info>
    
</rozklad>
